export enum LogSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  DEBUG = 'DEBUG',
  VERBOSE = 'VERBOSE',
}

export enum PlatformEvent {
  // Trading
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_EXECUTED = 'ORDER_EXECUTED',
  ORDER_REJECTED_SLIPPAGE = 'ORDER_REJECTED_SLIPPAGE',
  ORDER_REJECTED_STALE = 'ORDER_REJECTED_STALE',
  ORDER_REJECTED_FUNDS = 'ORDER_REJECTED_FUNDS',
  ORDER_IDEMPOTENCY_REPLAY = 'ORDER_IDEMPOTENCY_REPLAY',
  ORDER_OPTIMISTIC_ROLLBACK = 'ORDER_OPTIMISTIC_ROLLBACK',

  // WebSocket Lifecycle
  WS_CONNECT = 'WS_CONNECT',
  WS_DISCONNECT = 'WS_DISCONNECT',
  WS_AUTH_EXPIRED = 'WS_AUTH_EXPIRED',
  WS_AUTH_FAILED = 'WS_AUTH_FAILED',
  WS_AUTH_REFRESH = 'WS_AUTH_REFRESH',
  WS_RECONNECT_ABUSE = 'WS_RECONNECT_ABUSE',
  WS_SUBSCRIBE = 'WS_SUBSCRIBE',
  WS_UNSUBSCRIBE = 'WS_UNSUBSCRIBE',
  WS_DEGRADED = 'WS_DEGRADED',
  WS_SESSION_EXPIRED = 'WS_SESSION_EXPIRED',

  // Market Data
  MARKET_PROVIDER_FAILOVER = 'MARKET_PROVIDER_FAILOVER',
  MARKET_PROVIDER_TRIPPED = 'MARKET_PROVIDER_TRIPPED',
  MARKET_DATA_STALE = 'MARKET_DATA_STALE',
  MARKET_DATA_FETCH_FAILED = 'MARKET_DATA_FETCH_FAILED',
  MARKET_PROVIDER_MOCK_ACTIVATED = 'MARKET_PROVIDER_MOCK_ACTIVATED',
  MARKET_PROVIDER_LATENCY_SPIKE = 'MARKET_PROVIDER_LATENCY_SPIKE',

  // Redis
  REDIS_LOCK_FAILED = 'REDIS_LOCK_FAILED',
  REDIS_RECONNECT = 'REDIS_RECONNECT',
  REDIS_CACHE_FAILURE = 'REDIS_CACHE_FAILURE',
  REDIS_PUBSUB_FAILURE = 'REDIS_PUBSUB_FAILURE',

  // Cron & Analytics
  CRON_STARTED = 'CRON_STARTED',
  CRON_COMPLETED = 'CRON_COMPLETED',
  CRON_BATCH_FAILED = 'CRON_BATCH_FAILED',
  CRON_SNAPSHOT_GENERATED = 'CRON_SNAPSHOT_GENERATED',
  CRON_LEADERBOARD_REFRESHED = 'CRON_LEADERBOARD_REFRESHED',

  // Security & Abuse
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILED = 'AUTH_FAILED',
  ADMIN_ACCESS_DENIED = 'ADMIN_ACCESS_DENIED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // User Lifecycle
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTERED = 'USER_REGISTERED',

  // General App
  APP_EVENT = 'APP_EVENT',
}

export enum MetricEvent {
  METRIC_WS_CONNECTION_COUNT = 'METRIC_WS_CONNECTION_COUNT',
  METRIC_PROVIDER_FAILOVER_COUNT = 'METRIC_PROVIDER_FAILOVER_COUNT',
  METRIC_STALE_QUOTE_COUNT = 'METRIC_STALE_QUOTE_COUNT',
  METRIC_ORDER_REJECTION_RATE = 'METRIC_ORDER_REJECTION_RATE',
  METRIC_REDIS_LOCK_CONTENTION = 'METRIC_REDIS_LOCK_CONTENTION',
}

export type AllEvents = PlatformEvent | MetricEvent;
